language: python

python:
  - '3.6'

install:
  - pip install 'matplotlib'
  - pip install 'graphviz'
  - pip install 'tensorflow'
  - pip install 'scikit-learn'
  - pip install 'tifffile'
  - pip install 'Pillow'
  - pip install 'scipy'
  - pip install 'numpy'
  - pip install 'opencv-python>=3.3.0'
  - travis_wait pip install 'torch'
  - pip install 'torchvision'
  - pip install 'pytest'
  - pip install 'flake8'
  - pip install 'cython'
  - pip install 'psutil'
  - pip install coveralls


script:
  - python setup.py sdist
  - flake8 --max-line-length=120 --ignore=E402, E251, E221, W291, F401, W391, W293
  - coverage run --source pytorch_unet -m pytest

after_success:
  - coveralls